version: 2.1

orbs:
  node: circleci/node@5.1.0
  win: circleci/windows@5.0.0

commands:
  install:
    steps:
      - node/install:
          node-version: "16.19.0"
      - run: nvm use 16.19.0
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ arch }}
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Update Version
                command: node script/update-version.js << pipeline.git.tag >>
            - run: npm install
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                command: npm install
                environment:
                  ELECTRON_MKSNAPSHOT_STABLE_FALLBACK: 1
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
  test:
    steps:
      - run: node --version
      - run: npm --version
      - run: npm test

jobs:
  test-linux:
    docker:
      - image: cimg/base:stable
    steps:
      - install
      - test
  test-mac:
    macos:
      xcode: "13.3.0"
    steps:
      - install
      - test
  test-windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - install
      - test
  release:
    docker:
      - image: cimg/node:18.14
    steps:
      - checkout
      - run:
          name: Update Version
          command: node script/update-version.js << pipeline.git.tag >>
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Obtain Publishing Credentials
          command: npx @continuous-auth/circleci-oidc-github-auth@1.0.4
      - run:
          name: Confirm Version Updated
          command: node -e "if (require('./package.json').version === '0.0.0-development') process.exit(1)"
      - run:
          name: Set NPM Credentials
          command: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc
      - run:
          name: Check NPM Credentials
          command: npm whoami
      - run:
          name: CFA Publish
          command: node script/publish.js

workflows:
  test_and_release:
    jobs:
      - test-linux:
          filters:
            tags:
              only: /.*/
      - test-mac:
          filters:
            tags:
              only: /.*/
      - test-windows:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test-linux
            - test-mac
            - test-windows
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: cfa-release
