name: Publish npm Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      electron-version: ${{ github.ref_name }}
  release:
    runs-on: ubuntu-latest
    needs: test
    environment: npm
    permissions:
      contents: write # for creating new release
      id-token: write # for publishing releases
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "20.16.0"
      - name: Update npm to version that supports trusted publishing
        run: npm install -g npm@^11.5.1
      - name: Update Version
        run: node script/update-version.js ${{ github.ref_name }}
      - name: Confirm Version Updated
        run: node -e "if (require('./package.json').version === '0.0.0-development') process.exit(1)"
      - name: Install Dependencies
        run: npm ci
      - name: Publish to npm
        run: npm publish
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} -t ${{ github.ref_name }}
